default_platform(:ios)

platform :ios do
    desc "Run unit tests"
    lane :unit_test do
        swiftlint(
            mode: :lint,
            output_file: "fastlane/test_output/swiftlint.result.json",
            reporter: "json",
            config_file: ".swiftlint-ci.yml"
        )
        run_tests(
            devices: ["iPhone 8"],
            code_coverage: true,
            scheme: "devops_training"
        )
        slather(
            proj: "devops_training.xcodeproj",
            scheme: "devops_training",
            cobertura_xml: true,
            output_directory: "fastlane/test_output"
        )
    end
end
